version: "3.4"

services:
  react-vite-prod:
    image: ${DOCKER_REGISTRY-}react-vite-prod
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4173:3000
