version: "3.8"
services:
  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    container_name: products.api
    build:
      context: ../iconic-be
      dockerfile: Products.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    expose:
      - 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000

  nginx:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ../iconic-fe/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - products.api
