version: "3.4"

services:
  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    container_name: products.api
    build:
      context: .
      dockerfile: Products.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    expose:
      - 5000
    depends_on:
      products.database:
        condition: service_healthy

  products.database:
    image: postgres:latest
    container_name: products.database
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
